services:
  gitlab:
    image: gitlab/gitlab-ce:18.0.1-ce.0
    container_name: gitlab
    hostname: gitlab.local
    restart: always
    ports:
      - "80:80"
      - "8443:443"
      - "2222:22"
    volumes:
      - ${HOME}/gitlab/config:/etc/gitlab
      - ${HOME}/gitlab/logs:/var/log/gitlab
      - ${HOME}/gitlab/data:/var/opt/gitlab
    tmpfs:
      - /dev/shm:exec,size=256M  # 设置 /dev/shm 的大小为 1GB 并启用 exec

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    extra_hosts:
      #- "gitlab.local:172.16.225.138"   # 或宿主机真实 IP
      - "gitlab.local:127.0.0.1"
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
